apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: eks
spec:
  rules:
    - host: eks.siglus.us
      http:
        paths:
          - backend:
              serviceName: magpie
              servicePort: 80
            path: /
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: magpie
  name: magpie
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: magpie
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magpie
  name: magpie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magpie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: magpie
    spec:
      containers:
      - image: bywang/magpie
        name: magpie
        ports:
          - containerPort: 80